### ISSUE TITLE
Error when trying to restart after installing

### ISSUE THREAD

**Issue by PeaceNira** [chr314/nautilus-copy-path#51]
Traceback (most recent call last):
  File "/home/anon/.local/share/nautilus-python/extensions/nautilus-copypath.py", line 16, in <module>
    gi.require_versions({
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 149, in require_versions
    require_version(module_name, module_version)
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Nautilus is already loaded with version 3.0

nautilus launches but without the copy options.

**Comment by chr314** [comment]
install the 1.8.0 version which supports gtk 3
