### ISSUE TITLE
Extension does not work on RHEL 9.2

### ISSUE THREAD

**Issue by przmv** [chr314/nautilus-copy-path#52]
```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

```
$ dnf info nautilus-python python3-gobject
Last metadata expiration check: 0:00:53 ago on Wed 15 Nov 2023 10:38:09 PM MSK.
Installed Packages
Name         : nautilus-python
Version      : 1.2.3
Release      : 10.el9
Architecture : x86_64
Size         : 60 k
Source       : nautilus-python-1.2.3-10.el9.src.rpm
Repository   : @System
From repo    : epel
Summary      : Python bindings for Nautilus
URL          : https://wiki.gnome.org/Projects/NautilusPython
License      : GPLv2+
Description  : Python bindings for Nautilus

Name         : python3-gobject
Version      : 3.40.1
Release      : 6.el9
Architecture : x86_64
Size         : 24 k
Source       : pygobject3-3.40.1-6.el9.src.rpm
Repository   : @System
From repo    : AppStream
Summary      : Python 3 bindings for GObject Introspection
URL          : https://wiki.gnome.org/Projects/PyGObject
License      : LGPLv2+ and MIT
Description  : The python3-gobject package provides a convenient wrapper for the GObject
             : library and and other libraries that are compatible with GObject Introspection,
             : for use in Python 3 programs.
```

```
$ make install 
mkdir -p ~/.local/share/nautilus-python/extensions/nautilus-copy-path
cp nautilus-copy-path.py ~/.local/share/nautilus-python/extensions
cp nautilus_copy_path.py translation.py config.json ~/.local/share/nautilus-python/extensions/nautilus-copy-path
cp -rf translations ~/.local/share/nautilus-python/extensions/nautilus-copy-path
Restarting nautilus
Traceback (most recent call last):
  File "/home/petr/.local/share/nautilus-python/extensions/nautilus-copy-path.py", line 4, in <module>
    from nautilus_copy_path import NautilusCopyPath
  File "/home/petr/.local/share/nautilus-python/extensions/nautilus-copy-path/nautilus_copy_path.py", line 9, in <module>
    require_version('Gtk', '4.0')
  File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 3.0
```

**Comment by chr314** [comment]
install the [1.8.0](https://github.com/chr314/nautilus-copy-path/releases/tag/1.8.0) version
